@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><div class="cbis-eyebrow">Personal portal</div><h1 class="cbis-page-title">Welcome, {{ $user->first_name ?: $user->name }}</h1><p class="text-muted">One account for your selected blood services.</p></div><div class="d-flex gap-2"><a href="{{ route('account.profile.edit') }}" class="btn btn-outline-secondary">Manage Services</a>@if($user->hasPatientAccess())<a href="{{ route('reservations.create') }}" class="btn btn-danger">Request Blood</a>@endif</div></div>
<div class="row g-4">
@if($user->hasDonorAccess())<div class="col-lg-6"><div class="card h-100"><div class="card-header fw-bold">Donation Services</div><div class="card-body"><dl class="row mb-3"><dt class="col-6">Blood type</dt><dd class="col-6">{{ $donor?->blood_type ?? 'Not recorded' }}</dd><dt class="col-6">Eligibility</dt><dd class="col-6">{{ $donor?->is_eligible ? 'Eligible' : 'Not yet confirmed' }}</dd><dt class="col-6">Donations</dt><dd class="col-6">{{ $donationHistory->count() }}</dd></dl><div class="d-flex flex-wrap gap-2"><a href="{{ route('public.map') }}" class="btn btn-danger">Find Events on Map</a><a href="{{ route('donor.events.index') }}" class="btn btn-outline-danger">My Registrations</a></div></div></div></div>@endif
@if($user->hasPatientAccess())<div class="col-lg-6"><div class="card h-100"><div class="card-header fw-bold">Blood Requests</div><div class="card-body"><p class="text-muted">Submit requirements and follow the status of each request.</p><div class="fs-3 fw-bold mb-3">{{ $reservations->count() }} <span class="fs-6 fw-normal text-muted">request(s)</span></div><a href="{{ route('reservations.index') }}" class="btn btn-outline-danger">View Reservations</a></div></div></div>@endif
</div>
@if($user->hasDonorAccess())<div class="card mt-4"><div class="card-header fw-bold">Recent Donation History</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Donation No.</th><th>Date</th><th>Blood Type</th><th>Status</th></tr></thead><tbody>@forelse($donationHistory->take(5) as $record)<tr><td>{{ $record->donation_no }}</td><td>{{ $record->donated_at?->format('M d, Y') }}</td><td>{{ $record->blood_type }}</td><td>{{ ucfirst($record->status) }}</td></tr>@empty<tr><td colspan="4" class="text-muted">Completed donations recorded by staff will appear here.</td></tr>@endforelse</tbody></table></div></div>@endif
@if($user->notifications()->exists())<div class="card mt-4"><div class="card-header fw-bold">Recent Notifications</div><div class="list-group list-group-flush">@foreach($user->notifications()->latest()->limit(5)->get() as $notification)<div class="list-group-item"><strong>{{ $notification->data['title'] ?? 'Update' }}</strong><div class="small text-muted">{{ $notification->data['message'] ?? $notification->created_at?->diffForHumans() }}</div></div>@endforeach</div></div>@endif
@endsection
