@extends('layouts.app')
@section('content')
<div class="cbis-dashboard-heading"><div><div class="cbis-eyebrow">Your account</div><h1 class="cbis-page-title">My Profile</h1><p class="cbis-page-subtitle">Your personal information, shared across your selected services.</p></div><a href="{{ route('account.dashboard') }}" class="btn btn-outline-secondary">Back to Home</a></div>
<div class="row g-4"><div class="col-lg-8"><form method="POST" action="{{ route('account.details.update') }}" class="card">@csrf @method('PUT')
<div class="card-header cbis-card-title"><span>Personal Information</span></div><div class="card-body"><div class="row g-3">
@foreach(['first_name' => 'First name', 'middle_name' => 'Middle name', 'last_name' => 'Last name'] as $field => $label)<div class="col-md-4"><label for="{{ $field }}" class="form-label">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" class="form-control" maxlength="80" value="{{ old($field, $user->$field) }}" @required($field !== 'middle_name')></div>@endforeach
<div class="col-12"><label class="form-label">Address</label><x-negros-occidental-address-fields :address="old('address', $user->address)" /></div>
<div class="col-md-6"><label class="form-label" for="profileEmail">Email</label><input id="profileEmail" name="email" type="email" class="form-control" maxlength="255" value="{{ old('email', $user->email) }}" required><small class="text-muted">Use this email to sign in after saving.</small></div>
<div class="col-md-6"><label class="form-label" for="profilePhone">Mobile number</label><div class="input-group"><span class="input-group-text">09</span><input id="profilePhone" name="phone" class="form-control js-mobile-suffix" inputmode="numeric" maxlength="9" pattern="\d{9}" value="{{ \App\Support\PhilippinePhone::mobileSuffix(old('phone', $user->phone)) }}" placeholder="123456789" required></div><small class="text-muted">Enter the 9 digits after 09.</small></div>
</div><button class="btn btn-danger mt-4" type="submit">Save Profile</button></div></form></div>
<div class="col-lg-4"><section class="card"><div class="card-header cbis-card-title"><span>My Services</span></div><div class="card-body"><p>{{ $user->hasDonorAccess() && $user->hasPatientAccess() ? 'Patient/Donor services are enabled.' : ($user->hasDonorAccess() ? 'Donor services are enabled.' : 'Patient services are enabled.') }}</p><a class="btn btn-outline-danger" href="{{ route('account.profile.edit') }}">Manage Services</a></div></section>
@if($user->donorProfile)<section class="card mt-3"><div class="card-body"><small class="text-muted">Recorded blood type</small><h2 class="h4 mt-2">{{ $user->donorProfile->blood_type }}</h2><p class="small text-muted mb-0">Blood Bank Staff confirms your donation eligibility.</p></div></section>@endif
</div></div>
@endsection
